### ISSUE TITLE
ATM breaking

### ISSUE THREAD

**Issue by AGuyNamedJens** [FifouBE/EconomyInc#4]
ATMs can be easily broken with just one hit from both OPs and non-ops, how do i prevent that?

**Comment by Florent98** [comment]
Hello, it's not supposed to work like that. It's normally unbreakable. Thanks for the report I'm gonna look into it.

EDIT : After some checking, I'm not able to break it. Ops have the ability to break it since they are operators and often 'admins'. For non-ops it's not possible to break it. In which versions are you ?

**Comment by AGuyNamedJens** [comment]
The latest version of the mod

**Comment by AGuyNamedJens** [comment]
on forge forge-1.12.2-14.23.5.2831-universal

**Comment by Florent98** [comment]
EconomyInc 1.5 - MC1.12.2 (src: https://www.curseforge.com/minecraft/mc-mods/economy-inc/files/2526391) this one ?

**Comment by Florent98** [comment]
Ok I have found the version that is responsible, I will fix that and push it to curse as soon as I can thanks for the report!

**Comment by AGuyNamedJens** [comment]
Yeah the latest 1.12.2 one, thanks!

**Comment by AGuyNamedJens** [comment]
How do people get their own money without me cheating it in? i can't get that to work btw

**Comment by Florent98** [comment]
New update I'm going to push for minecraft 1.12 is the version 1.6.1 so the latest version of the mod (which is still being updated for 1.14 but soon released) have a new way of working. By smelting a gold ingot you will now obtain the pure gold nugget that has a certain weight. When processing that gold nugget into the block changer your credit card will be updated. For you as an admin you have the config file line "multiplierGoldNuggetWeight" by changing this value you are affecting how much someone can get from a weight. Example : your gold nugget weight 1.00, let's imagine you put the multiplierGoldNuggetWeight at 5. The person will earn (1.00 * 5), so he'll earn 5 dollars. I hope it's clear, if you don't want that you can disable totally that option by turning 'goldNuggetRecipe' line to false.

**Comment by AGuyNamedJens** [comment]
Oh okay cool. I just melted one ore, but appearently putting that nugget in the gold exchanger gets my credit card a worth of something like 5.55999999999 rather than 5.55 or 5.56, can that also be fixed?

**Comment by Florent98** [comment]
It happens sometimes that the value would get infinite decimal. That's a thing that will be removed, but not for now, it's a "detail" so it will be updated last. But yes it will :)

**Comment by AGuyNamedJens** [comment]
Okay cool, and i just got this error when i tried accessing the same gold exchanger someone else was using. `[14:01:54] [Server thread/FATAL] [minecraft/MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: net/minecraft/client/resources/I18n
        at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_231]
        at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_231]
        at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/resources/I18n
        at fr.fifou.economy.blocks.BlockChanger.func_180639_a(BlockChanger.java:91) ~[BlockChanger.class:?]
        at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:449) ~[or.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:741) ~[pa.class:?]
        at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:55) ~[ma.class:?]
        at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:11) ~[ma.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_231]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_231]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
        ... 5 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.resources.I18n
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_231]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_231]
        at fr.fifou.economy.blocks.BlockChanger.func_180639_a(BlockChanger.java:91) ~[BlockChanger.class:?]
        at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:449) ~[or.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:741) ~[pa.class:?]
        at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:55) ~[ma.class:?]
        at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:11) ~[ma.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_231]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_231]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
        ... 5 more
Caused by: java.lang.NullPointerException`

**Comment by Florent98** [comment]
I'll look into that, it's a weird crash..

**Comment by AGuyNamedJens** [comment]
I also just found a village's bank, bought the code but its not working lol..

**Comment by AGuyNamedJens** [comment]
okay appearently you need a vault cracker for that to work

**Comment by Florent98** [comment]
Yes, you need a special tool. The digital vault cracker.

**Comment by AGuyNamedJens** [comment]
I cant seem to find out how to use the vending machine to BUY items for money rather than selling items for money, like an admin shop

**Comment by Florent98** [comment]
You can buy with money from a seller, but you cannot sell an item to the seller to receive money. You have to make your own seller with what you are selling for a certain price for that. And you can click on the "unlimited stack" above the gui when creating it, so the seller won't run out of resources. But that's an interesting idea to add :)
